services:
  db:
    image: ankane/pgvector:latest
    container_name: aingine-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9999
      - POSTGRES_DB=aingine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: